##########Services#########################
###########################################
services:

##########Backend (FastAPI)################
  web:
    build:
      context: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
###########################################
##########PostgreSQL####################### 
  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost"]
      interval: 1s
      timeout: 5s
      retries: 10
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
###########################################
##########Redis############################
  redis:
    image: redis:alpine

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
###########################################
##########Celery###########################
  worker:
    build:
      context: ./backend
    command: celery -A worker.celery_app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - db
    volumes:
      - ./backend:/app
###########################################
##########Ollama###########################
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: all
              capabilities: ["gpu"]
###########################################
##########Vite#############################
  frontend:
    build:
      context: ./frontend
    environment:
      NODE_ENV: development
    ports:
      - 5173:5173
###########################################
volumes:
  postgres_data:
  ollama_data:
